# Generated by Django 6.0.2 on 2026-02-09 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=100)),
                ('rarity', models.CharField(max_length=50)),
                ('border1', models.CharField(max_length=7)),
                ('border2', models.CharField(max_length=7)),
                ('holo', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='usercard',
            name='card_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card'),
        ),
    ]
