# Generated by Django 6.0.2 on 2026-02-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_card_alter_usercard_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercard',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
