# Generated by Django 6.0.2 on 2026-02-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usercard_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercard',
            old_name='card_id',
            new_name='card',
        ),
    ]
