# Generated by Django 6.0.2 on 2026-02-11 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trade'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trade',
            new_name='Trades',
        ),
    ]
