# Generated by Django 6.0.2 on 2026-02-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_trade_trades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trades',
            new_name='Trade',
        ),
    ]
